// <auto-generated />
using System;
using System.Collections.Generic;
using EssayChecker.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EssayChecker.Persistence.Migrations
{
    [DbContext(typeof(EssayDbContext))]
    [Migration("20260823084502_AddDeviceTrials")]
    partial class AddDeviceTrials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EssayChecker.Domain.Entities.Essays.Essay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccuracyPercent")
                        .HasColumnType("integer");

                    b.Property<string>("CorrectedEssay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("InputSource")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("StudentId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("TotalScore")
                        .HasColumnType("double precision");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .HasFilter("\"StudentId\" IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("Essays", (string)null);
                });

            modelBuilder.Entity("EssayChecker.Domain.Entities.Lessons.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NormalizedTopic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PromptVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("NormalizedTopic", "Grade")
                        .IsUnique();

                    b.ToTable("Lessons", (string)null);
                });

            modelBuilder.Entity("EssayChecker.Domain.Entities.Logs.RequestLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("QueryString")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("RequestBody")
                        .HasColumnType("text");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Path");

                    b.HasIndex("StatusCode");

                    b.HasIndex("UserId");

                    b.ToTable("RequestLogs", (string)null);
                });

            modelBuilder.Entity("EssayChecker.Domain.Entities.Marketing.EnglishTeacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ContactedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsContacted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ProfileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("IsContacted");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("EnglishTeachers", (string)null);
                });

            modelBuilder.Entity("EssayChecker.Domain.Entities.Subscriptions.DailyUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LessonCount")
                        .HasColumnType("integer");

                    b.Property<int>("OcrCheckCount")
                        .HasColumnType("integer");

                    b.Property<int>("TextCheckCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("UsageDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "UsageDate")
                        .IsUnique();

                    b.ToTable("DailyUsages", (string)null);
                });

            modelBuilder.Entity("EssayChecker.Domain.Entities.Subscriptions.DeviceTrial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceIdHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GrantedToUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeviceIdHash")
                        .IsUnique();

                    b.ToTable("DeviceTrials", (string)null);
                });

            modelBuilder.Entity("EssayChecker.Domain.Entities.Subscriptions.ProcessedGoogleNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("ProcessedGoogleNotifications", (string)null);
                });

            modelBuilder.Entity("EssayChecker.Domain.Entities.Subscriptions.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkedPurchaseToken")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProductId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PurchaseToken")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("PurchaseTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseTokenHash");

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("UserSubscriptions", (string)null);
                });

            modelBuilder.Entity("EssayChecker.Domain.Entities.Teaching.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Grade")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("EssayChecker.Domain.Entities.Teaching.StudentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.ToTable("StudentGroups", (string)null);
                });

            modelBuilder.Entity("EssayChecker.Domain.Entities.Users.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ReferralCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("ReferralRewardGranted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("ReferredByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("ReferralCode")
                        .IsUnique()
                        .HasFilter("\"ReferralCode\" IS NOT NULL");

                    b.HasIndex("ReferredByUserId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EssayChecker.Domain.Entities.Users.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EssayChecker.Domain.Entities.Essays.Essay", b =>
                {
                    b.HasOne("EssayChecker.Domain.Entities.Teaching.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EssayChecker.Domain.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("EssayChecker.Domain.Entities.Essays.EssayMistake", "Mistakes", b1 =>
                        {
                            b1.Property<int>("EssayId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("Category")
                                .HasColumnType("integer");

                            b1.Property<string>("Correct")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Wrong")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("EssayId", "Id");

                            b1.ToTable("Essays");

                            b1.ToJson("Mistakes");

                            b1.WithOwner()
                                .HasForeignKey("EssayId");
                        });

                    b.OwnsOne("EssayChecker.Domain.Entities.Essays.EssayScores", "Scores", b1 =>
                        {
                            b1.Property<int>("EssayId")
                                .HasColumnType("integer");

                            b1.Property<double>("Content")
                                .HasColumnType("double precision");

                            b1.Property<string>("ContentComment")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<double>("Grammar")
                                .HasColumnType("double precision");

                            b1.Property<string>("GrammarComment")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<double>("Structure")
                                .HasColumnType("double precision");

                            b1.Property<string>("StructureComment")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<double>("Total")
                                .HasColumnType("double precision");

                            b1.Property<double>("Vocabulary")
                                .HasColumnType("double precision");

                            b1.Property<string>("VocabularyComment")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.HasKey("EssayId");

                            b1.ToTable("Essays");

                            b1.WithOwner()
                                .HasForeignKey("EssayId");
                        });

                    b.OwnsOne("EssayChecker.Domain.Entities.Essays.EssayStatistics", "Statistics", b1 =>
                        {
                            b1.Property<int>("EssayId")
                                .HasColumnType("integer");

                            b1.Property<int>("Grammar")
                                .HasColumnType("integer");

                            b1.Property<int>("NaturalExpression")
                                .HasColumnType("integer");

                            b1.Property<int>("Spelling")
                                .HasColumnType("integer");

                            b1.Property<int>("Total")
                                .HasColumnType("integer");

                            b1.Property<int>("Vocabulary")
                                .HasColumnType("integer");

                            b1.HasKey("EssayId");

                            b1.ToTable("Essays");

                            b1.WithOwner()
                                .HasForeignKey("EssayId");
                        });

                    b.OwnsOne("EssayChecker.Domain.Entities.Essays.TeacherFeedback", "Feedback", b1 =>
                        {
                            b1.Property<int>("EssayId")
                                .HasColumnType("integer");

                            b1.Property<List<string>>("Recommendations")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<List<string>>("Strengths")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<List<string>>("Weaknesses")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.HasKey("EssayId");

                            b1.ToTable("Essays");

                            b1.ToJson("Feedback");

                            b1.WithOwner()
                                .HasForeignKey("EssayId");
                        });

                    b.Navigation("Feedback")
                        .IsRequired();

                    b.Navigation("Mistakes");

                    b.Navigation("Scores")
                        .IsRequired();

                    b.Navigation("Statistics")
                        .IsRequired();
                });

            modelBuilder.Entity("EssayChecker.Domain.Entities.Lessons.Lesson", b =>
                {
                    b.HasOne("EssayChecker.Domain.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("EssayChecker.Domain.Entities.Lessons.LessonQuizQuestion", "Quiz", b1 =>
                        {
                            b1.Property<int>("LessonId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("CorrectIndex")
                                .HasColumnType("integer");

                            b1.Property<string>("Explanation")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<List<string>>("Options")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<string>("Question")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("LessonId", "Id");

                            b1.ToTable("Lessons");

                            b1.ToJson("Quiz");

                            b1.WithOwner()
                                .HasForeignKey("LessonId");
                        });

                    b.OwnsMany("EssayChecker.Domain.Entities.Lessons.LessonSlide", "Slides", b1 =>
                        {
                            b1.Property<int>("LessonId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Body")
                                .HasColumnType("text");

                            b1.Property<string>("Formula")
                                .HasColumnType("text");

                            b1.Property<List<string>>("Keywords")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<List<string>>("Points")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("LessonId", "Id");

                            b1.ToTable("Lessons");

                            b1.ToJson("Slides");

                            b1.WithOwner()
                                .HasForeignKey("LessonId");

                            b1.OwnsOne("EssayChecker.Domain.Entities.Lessons.LessonComparison", "Comparison", b2 =>
                                {
                                    b2.Property<int>("LessonSlideLessonId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("LessonSlideId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("LeftBody")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("LeftTitle")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("RightBody")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("RightTitle")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("LessonSlideLessonId", "LessonSlideId");

                                    b2.ToTable("Lessons");

                                    b2.WithOwner()
                                        .HasForeignKey("LessonSlideLessonId", "LessonSlideId");
                                });

                            b1.OwnsMany("EssayChecker.Domain.Entities.Lessons.LessonExample", "Examples", b2 =>
                                {
                                    b2.Property<int>("LessonSlideLessonId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("LessonSlideId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Az")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("En")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Highlight")
                                        .HasColumnType("text");

                                    b2.HasKey("LessonSlideLessonId", "LessonSlideId", "Id");

                                    b2.ToTable("Lessons");

                                    b2.WithOwner()
                                        .HasForeignKey("LessonSlideLessonId", "LessonSlideId");
                                });

                            b1.OwnsMany("EssayChecker.Domain.Entities.Lessons.LessonMistakeItem", "Mistakes", b2 =>
                                {
                                    b2.Property<int>("LessonSlideLessonId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("LessonSlideId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Correct")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Note")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Wrong")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("LessonSlideLessonId", "LessonSlideId", "Id");

                                    b2.ToTable("Lessons");

                                    b2.WithOwner()
                                        .HasForeignKey("LessonSlideLessonId", "LessonSlideId");
                                });

                            b1.Navigation("Comparison");

                            b1.Navigation("Examples");

                            b1.Navigation("Mistakes");
                        });

                    b.Navigation("Quiz");

                    b.Navigation("Slides");
                });

            modelBuilder.Entity("EssayChecker.Domain.Entities.Subscriptions.DailyUsage", b =>
                {
                    b.HasOne("EssayChecker.Domain.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EssayChecker.Domain.Entities.Subscriptions.UserSubscription", b =>
                {
                    b.HasOne("EssayChecker.Domain.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EssayChecker.Domain.Entities.Teaching.Student", b =>
                {
                    b.HasOne("EssayChecker.Domain.Entities.Teaching.StudentGroup", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("EssayChecker.Domain.Entities.Teaching.StudentGroup", b =>
                {
                    b.HasOne("EssayChecker.Domain.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EssayChecker.Domain.Entities.Users.RefreshToken", b =>
                {
                    b.HasOne("EssayChecker.Domain.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("EssayChecker.Domain.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("EssayChecker.Domain.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EssayChecker.Domain.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("EssayChecker.Domain.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EssayChecker.Domain.Entities.Teaching.StudentGroup", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
